# Generated by Django 4.1 on 2023-05-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
