# Generated by Django 4.1 on 2023-06-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usapp', '0004_remove_folder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usapp.folder'),
        ),
    ]
