# Generated by Django 4.1 on 2023-06-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usapp', '0005_text_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='folder',
            new_name='parentId',
        ),
    ]
