# Generated by Django 4.1 on 2023-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usapp', '0007_folder_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(default='Folder', max_length=6),
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.CharField(default='Text', max_length=4),
        ),
    ]
